Repository exercism/c, pull requests merged in 2021-03, with the labels that each got.

#630 Linked list
  exercises/practice/linked-list/.meta/example.c
  exercises/practice/linked-list/.meta/example.h
  exercises/practice/linked-list/.meta/tests.toml
  exercises/practice/linked-list/linked_list.c
  exercises/practice/linked-list/linked_list.h
  exercises/practice/linked-list/test_linked_list.c
Labels: enhancement

#636 Update docs for CI
  docs/ABOUT.md
  docs/CONTRIBUTING.md
  docs/C_STYLE_GUIDE.md
  docs/INSTALLATION.md
  docs/LEARNING.md
  docs/RESOURCES.md
  docs/TESTS.md
  docs/VERSIONS.md
Labels: documentation

#637 🤖 Add docs configuration
  docs/config.json
Labels: v3-migration 🤖
