Repository exercism/c, pull requests merged in 2021-05, with the labels that each got.

#644 hamming: update tests.toml
  exercises/practice/hamming/.meta/tests.toml
Labels: enhancement

#643 isogram: Add new test
  exercises/practice/isogram/.meta/tests.toml
  exercises/practice/isogram/test_isogram.c
Labels: enhancement

#641 luhn: Add new test
  exercises/practice/luhn/.meta/tests.toml
  exercises/practice/luhn/test_luhn.c
Labels: enhancement

#642 anagram: Add new test
  exercises/practice/anagram/.meta/tests.toml
  exercises/practice/anagram/test_anagram.c
Labels: enhancement

#613 Add key features
  config.json
Labels: v3-migration 🤖

#648 hamming: remove duplicate key
  exercises/practice/hamming/.meta/tests.toml
Labels: bug

#649 linked-list: update tests.toml to new spec
  exercises/practice/linked-list/.meta/tests.toml
Labels: bug

#647 🤖 Add fetch configlet script(s) to CODEOWNERS file
  .github/CODEOWNERS
Labels: v3-migration 🤖

#651 🤖 Update test runner status
  config.json
Labels: v3-migration 🤖

#652 Mention test runner
  docs/CONTRIBUTING.md
Labels: documentation

#655 Remove example.h from configs where file doesnt exist
  exercises/practice/acronym/.meta/config.json
  exercises/practice/anagram/.meta/config.json
  exercises/practice/clock/.meta/config.json
  exercises/practice/collatz-conjecture/.meta/config.json
  exercises/practice/complex-numbers/.meta/config.json
  exercises/practice/hello-world/.meta/config.json
  exercises/practice/isogram/.meta/config.json
  exercises/practice/pangram/.meta/config.json
  exercises/practice/queen-attack/.meta/config.json
  exercises/practice/rail-fence-cipher/.meta/config.json
  exercises/practice/react/.meta/config.json
  exercises/practice/robot-simulator/.meta/config.json
  exercises/practice/series/.meta/config.json
  exercises/practice/sieve/.meta/config.json
  exercises/practice/sublist/.meta/config.json
  exercises/practice/word-count/.meta/config.json
Labels: bug

#654 🤖 Add average test runner run time to `config.json`
  config.json
Labels: v3-migration 🤖

#658 🤖 Remove `online_editor.ace_editor_language` key
  config.json
Labels: v3-migration 🤖

#659 🤖 Add labels append file
  .appends/.github/labels.yml
Labels: v3-migration 🤖
